1 CREATE VIEW EMP_VIEW AS
SELECT *
FROM EMPLOYEE;
2 CREATE VIEW EMP_BASICS AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY
FROM EMPLOYEES;
3  SELECT *
FROM EMP_VIEW;
4 CREATE VIEW IT_EMPLOYEE AS
SELECT *
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT';
 5 CREATE VIEW HIGH_SALARY AS
SELECT *
FROM EMPLOYEE
WHERE SALARY > 60000;
 6 CREATE VIEW HYDERABAD_EMP AS
SELECT *
FROM EMPLOYEES
WHERE CITY = 'Hyderabad';
 7 CREATE VIEW FEMALE_EMP AS
SELECT *
FROM EMPLOYEES
WHERE GENDER = 'Female';
8 CREATE VIEW RECENT_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE >= DATE '2020-01-01';
9 SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
FROM HIGH_SALARY;
10 CREATE OR REPLACE VIEW EMP_BASIC AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
       DEPARTMENT, SALARY, CITY
FROM EMPLOYEES;
 11 CREATE VIEW EMP_SALARY_VIEW AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WITH READ ONLY;
 12 CREATE VIEW SALES_EMP AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'Sales'
WITH CHECK OPTION;
 13 UPDATE EMP_BASIC
SET SALARY = 70000
WHERE EMPLOYEE_ID = 101;
 14 DELETE FROM EMP_VIEW
WHERE EMPLOYEE_ID = 107;
 15 INSERT INTO EMP_BASIC
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY, CITY)
VALUES
(111, 'Neha', 'Reddy', 'IT', 65000, 'Hyderabad');
 16 DESC EMP_BASIC;
 17 SELECT *
FROM IT_EMPLOYEE;
 18 SELECT *
FROM HIGH_SALARY
WHERE SALARY > 70000;
 19 SELECT *
FROM FEMALE_EMP;
20  SELECT FIRST_NAME, LAST_NAME, SALARY
FROM HYDERABAD_EMP;
21 DROP VIEW EMP_VIEW;
22 DROP VIEW HIGH_SALARY;
23 DROP VIEW EMP_BASIC;
24  CREATE VIEW HR_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT = 'HR';
25 CREATE VIEW MARKETING_EMP AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
       DEPARTMENT, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT = 'Marketing';
26  CREATE VIEW TOP_EARNERS AS
SELECT *
FROM EMPLOYEES
WHERE SALARY > 70000;
27  CREATE VIEW EMP_CITY AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, CITY
FROM EMPLOYEES;